### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by raj-subhankar** [raj-subhankar/Pokesnap#4]
Add a CONTRIBUTING.md file similar too https://github.com/raj-subhankar/HumansOfGitHub/blob/master/CONTRIBUTING.md

**Comment by ajeetrocks100** [comment]
Hey, I tried to resolve some issue with #6 file. did I mess up?

**Comment by danielksan81** [comment]
will do it

**Comment by ventris** [comment]
I would like to help you with this.

**Comment by sudoankit** [comment]
I will do it. Give me the day.

**Comment by RickRedSix** [comment]
I have added your contributing.md file #6

**Comment by IgnorantSapient** [comment]
I have added a contributing.md as well #7
